# Generated by Django 4.1.2 on 2022-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_imageupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='image_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
